#ifndef TSHOTBLOCKS_H__
#define TSHOTBLOCKS_H__

enum
{
    SHOTBLOCKS_ENABLED              = 1000,
    SHOTBLOCKS_MODE                 = 1001,
    SHOTBLOCKS_MODE_ADDITIVE        = 0,
    SHOTBLOCKS_MODE_REPLACE         = 1,
    SHOTBLOCKS_DAMPING_POS          = 1002,
    SHOTBLOCKS_DAMPING_ROT          = 1003,
    SHOTBLOCKS_SUBSTEP_THRESHOLD    = 1006,
    SHOTBLOCKS_RESET_ON_BOUNDARY    = 1008,
    SHOTBLOCKS_LOOK_AT_TARGET       = 1020,
    SHOTBLOCKS_UP_TARGET            = 1021,
    SHOTBLOCKS_LOOK_AT_STRENGTH     = 1022,
    SHOTBLOCKS_GRP_DAMPING          = 1100,
    SHOTBLOCKS_GRP_LOOK_AT          = 1102,
    SHOTBLOCKS_GRP_ADVANCED         = 1101,
};

#endif
