#ifndef TSHOTBLOCKS_H__
#define TSHOTBLOCKS_H__

enum
{
    SHOTBLOCKS_ENABLED              = 1000,
    // 1001 was SHOTBLOCKS_MODE (additive/replace cycle). Replace mode
    // was never built; the rig is additive-only. ID retired, not reused.
    SHOTBLOCKS_DAMPING_POS          = 1002,
    SHOTBLOCKS_DAMPING_ROT          = 1003,
    SHOTBLOCKS_SUBSTEP_THRESHOLD    = 1006,
    SHOTBLOCKS_RESET_ON_BOUNDARY    = 1008,
    SHOTBLOCKS_LOOK_AT_TARGET       = 1020,
    SHOTBLOCKS_UP_TARGET            = 1021,
    SHOTBLOCKS_LOOK_AT_STRENGTH     = 1022,
    SHOTBLOCKS_LOOK_AT_ROLL         = 1023,
    SHOTBLOCKS_BANK_INTO_TURNS      = 1024,
    SHOTBLOCKS_NOISE_ENABLED        = 1030,  // was SHOTBLOCKS_NOISE_PROFILE (off/handheld cycle); only one profile, so it's a bool now
    SHOTBLOCKS_NOISE_STRENGTH       = 1031,
    SHOTBLOCKS_NOISE_SEED           = 1032,
    SHOTBLOCKS_NOISE_WALKING        = 1033,
    SHOTBLOCKS_NOISE_STEP_RATE      = 1034,
    SHOTBLOCKS_NOISE_SPEED          = 1035,
    SHOTBLOCKS_ZOOM_ENABLED         = 1040,
    SHOTBLOCKS_ZOOM_RATE            = 1041,
    SHOTBLOCKS_ZOOM_STRENGTH        = 1042,
    SHOTBLOCKS_ZOOM_HOLD            = 1043,
    SHOTBLOCKS_ZOOM_RAMP_IN         = 1044,
    SHOTBLOCKS_ZOOM_RAMP_OUT        = 1045,
    SHOTBLOCKS_ZOOM_RETURN          = 1046,
    SHOTBLOCKS_FOLLOW_ENABLED       = 1050,
    SHOTBLOCKS_FOLLOW_TARGET        = 1051,
    SHOTBLOCKS_FOLLOW_DISTANCE      = 1052,
    SHOTBLOCKS_FOLLOW_VEL_SMOOTH    = 1053,
    SHOTBLOCKS_FOLLOW_REORIENT      = 1054,
    SHOTBLOCKS_FOLLOW_HEIGHT_BIAS   = 1055,
    SHOTBLOCKS_FOLLOW_SIDE_BIAS     = 1056,
    SHOTBLOCKS_FOLLOW_AIM_TRACK     = 1057,
    SHOTBLOCKS_FOLLOW_LEAD_DIST     = 1058,
    SHOTBLOCKS_FOLLOW_AIM_LEAD      = 1059,
    SHOTBLOCKS_GRP_DAMPING          = 1100,
    SHOTBLOCKS_GRP_LOOK_AT          = 1102,
    SHOTBLOCKS_GRP_FRAMING          = 1103,
    SHOTBLOCKS_GRP_NOISE            = 1104,
    SHOTBLOCKS_GRP_ZOOM             = 1105,
    SHOTBLOCKS_GRP_FOLLOW           = 1106,
    SHOTBLOCKS_GRP_ADVANCED         = 1101,
};

#endif
